name = "tom"
version = "1.1.0"

description = "A pure Gleam TOML parser!"
licences = ["Apache-2.0"]
repository = { type = "github", user = "lpil", repo = "tom" }
links = [{ title = "TOML website", href = "https://toml.io/en/" }]

[dependencies]
gleam_stdlib = ">= 0.33.0 and < 3.0.0"

[dev-dependencies]
gleeunit = "~> 1.0"
